### ISSUE TITLE
exception when creating geoip location string...

### ISSUE THREAD

**Issue by JustinCappos** [SeattleTestbed/seattlelib_v2#162]
It seems that our geoip library returns 'None' sometimes for things like the city name.  We are only expecting it to only omit the key.  As a result, we get exceptions like this:

dubdubdub@%all !> show location
%1(130.253.21.121): Denver, United States
%2(130.104.72.201): Louvain, Belgium
%3(210.32.181.184): Hangzhou, China
%4(128.220.231.2): Baltimore, United States
%5(128.223.8.112): Eugene, United States
Traceback (most recent call last):
  File "seash.py", line 267, in command_loop
  File "/Users/justincappos/Downloads/seattle_demokit/seash_dictionary.py", line 2109, in command_dispatch
  File "/Users/justincappos/Downloads/seattle_demokit/modules/geoip/__init__.py", line 56, in show_location
  File "/Users/justincappos/Downloads/seattle_demokit/geoip_client", line 130, in geoip_location_str
TypeError: cannot concatenate 'str' and 'NoneType' objects
dubdubdub@%all !> 

This should be fixed, most likely by just checking that the value is not None before appending into the string.

**Comment by aaaaalbert** [comment]
FYI, I've also updated the production demokits for [Seattle](http://seattleclearinghouse.poly.edu/dist/demokit.zip) and [Sensibility Testbed](https://sensibilityclearinghouse.poly.edu/demokit/sensibility-testbed-demokit.zip) to contain the fix.
